### ISSUE TITLE
Hardsphere potential with splines does not work

### ISSUE THREAD

**Issue by rc83** [rc83/faunus#2]
If ``nonbonded_exact`` is replaced by ``nonbonded`` in the following snippet, faunus hangs without any progress. There should be no difference between these methods, except precision.
```
energy:
- nonbonded_exact:
    default:
    - hardsphere: {}
```
